-- COPIA DE SEGURIDAD
-- 2 INSERTA EN LA TABLA CICLICAMENTE CADA 10 SEGUNTOS
-- REALIZA COPIA DE SEGURIDAD

SET GLOBAL EVENT_SCHEDULER = ON; 

DROP SCHEMA IF EXISTS TEST; 
CREATE SCHEMA TEST; 
USE TEST;

CREATE TABLE DATOS (
CODIGO INT PRIMARY KEY AUTO_INCREMENT, 
DATO INT, 
FECHA DATETIME DEFAULT CURRENT_TIMESTAMP
); 

INSERT INTO DATOS(DATO) VALUES (10), (20),(30),(40);
SELECT * FROM DATOS;

-- EVENTO

DROP EVENT IF EXISTS BACKUP_EVENT; 
CREATE EVENT BACKUP_EVENT
ON SCHEDULE EVERY 10 SECOND STARTS NOW()
DO
	CALL COPIAR_TABLA();
    

-- PROCEDIMIENTO
DROP PROCEDURE IF EXISTS COPIAR_RABLA; 
DELIMITER //
CREATE PROCEDURE COPIAR_TABLA()
BEGIN
	DROP TABLE IF EXISTS DATOS_BACKUP;
    -- CREA UNA TABLA "DATOS_BACKUP" CON LA MISMA ESTRUCTURA SIN DATOS! SOLO LA ESTRUCTURA
    CREATE TABLE DATOS_BACKUP LIKE DATOS; 
    -- INSERTA LOS DATOS
    INSERT DATOS_BACKUO SELECT * FROM DATOS

END // ; 

DELIMITER ; 

-- COMPROBACION 
SELECT * FROM DATOS; 
SELECT * FROM DATOS_BACKUP; 
UPDATE DATOS SET DATO = 0 WHERE CODIGO = 1; 
