CREATE DATABASE STEFA;
DROP PROCEDURE IF EXISTS semaforo;
USE STEFA; 

CREATE TABLE T(
	NUMERO INT PRIMARY KEY
);

DROP PROCEDURE IF EXISTS semaforo;

DELIMITER $$ 

CREATE procedure EJEMPLO_CASE ( IN DATO booLEAN)
BEGIN
-- SI RECIBIMOS EN EL PARAMETRO DEL PROCEDURE UN TRUE,
-- ANADIMOS 1 A LA TABLA T Y SI RECIBIMOS UN false, UN CERO

CASE DATO 
	WHEN TRUE THEN INSERT INTO T VALUES (1);
    WHEN FALSE THEN INSERT INTO T VALUES (0);
	ELSE SELECT "DATO ERRONEO"; 
    
	END CASE;  
END $$

DELIMITER ; 

CALL EJEMPLO_CASE ("FALSE");
SELECT * FROM T; 

-- NUEVO EJERCICIO DE NUMEROS DE TELEFONO

DELIMITER $$  

CREATE procedure TELEFONO (IN DATO INT (2))
BEGIN
	IF  DATO = 34 THEN SELECT "COMPLETA TU NUMERO DE MOVIL LOCAL";
    ELSE  SELECT "NO PUEDES SUSCRIBIRTE A NUESTRO CANAL FUERA DE ESPANA";
    END IF; 

END $$
DELIMITER ; 

CALL TELEFONO (34);

-- OTRA FORMA DE HACER EL EJERCICIO DEL TELEFONO
DELIMITER ; 

DROP procedure IF exists TELEFONO_PROFE;
CREATE procedure TELEFONO_PROFE (IN NUM_TEL VARCHAR(12))
BEGIN
	DECLARE PREFIJO VARCHAR (3);
	SET PREFIJO = SUBSTR (NUM_TEL, 1,3); 
    -- VARIANTE IF
    
    IF PREFIJO = "+34" THEN 
		SELECT "NRO CORRECTO" ; 
	ELSE 
		SELECT "NRO INCORRECTO"; 

END $$ 
DELIMITER ;

CALL TELEFONO_PROFE (+34610038513);

-- EJERCICIO WHILE
DROP procedure IF exists IMPRIME_NRO_O_10;
CREATE procedure IMPRIME_NRO_O_10 () -- aca en este parentesis puede ir el dato 'dinamico que coloque el usuario' . En esta opcion tal cual esta, estamos diciendo que la comparativa es con el numero 10, comparamos i con el 10. Si queremos que el loop quede definido por el valor de ingreso del usuario, colocamos en ese parentesis, por ejemplo, el nombre de la variable esa y el tipo de dato que es - ( in limite int) 

DECLARE I INT DEFAULT 1; 
	WHILE i<= 10 do -- comparacion - en java es // comp
	select import table fromset i= 1+i; -- actualizar - en java // act
    
END WHILE 
END $$ 
DELIMITER ; 

CALL IMPRIME_NRO_O_10 (); 
BEGIN

DELIMITER $$  

CREATE procedure INDOMITOS (IN PRESUPUESTO INT (7))
BEGIN
	IF  PRESUPUESTO < 7000  THEN SELECT "NO TRABAJAMOS POR TAN POCO DINERO";
    ELSE  SELECT "TU DOMO LLAVE EN MANO ESTARA LISTO EN 3O DIAS";
    END IF; 

END $$
DELIMITER ; 

CALL INDOMITOS (7000); 


DELIMITER $$  
DROP TABLE SOFIA
create table SOFIA (
	NOMBRE VARCHAR (35), EDAD INT, PAIS VARCHAR (20) PRIMARY KEY, LIBROS_LEIDOS INT); 
 INSERT INTO SOFIA 
	VALUES ("SOFIA MARIA DE LA SALETTE", 34, "PORTUGAL", 0), 
    ("SOFIA mARIA DE LA SALETTE", 33, "AUSTRALIA", 0),
    ("SOFIA MARIA DE LA SALETTE", 32, "SEVILLA", 0), 
    ("SOFIA MARIA DE LA SALETTE", 32, "NUEVA ZELANDA", 0); 
 
 SELECT * 
 FROM SOFIA; 
 
  drop procedure if exists SOFIA_LECTORA;
delimiter $$

create procedure SOFIA_LECTORA (in dato PAIS VARCHAR (30))
begin

	IF DATO 'AUSTRALIA' THEN SELECT "MUCHO PORRO POCAS HOJAS";
    IF DATO 'NUEVA ZELANDA' THEN SELECT  "MUCHO FOLLE CON EL HIPPIE" ;
    IF DATO 'SEVILLA' THEN SELECT "LEYENDO COSAS DEL MASTER"; 
    IF DATO 'PORTUGAL' THEN SELECT "SE SOSPECHA POSIBLE LECTURA"; 
    end case;
end $$

delimiter ;

CALL SOFIA_LECTORA (AUSTRALIA); 
  
  
  -- EJERCICIO INVENTADO POR MI 
drop procedure if exists SOFIA_NO_QUIERE_LEER;
delimiter $$
create procedure SOFIA_NO_QUIERE_LEER (in dato boolean)
begin

	WHEN DATO TRUE THEN SELECT "SI SIGUE LEYENDO, SERA UNA GRAN ESCRITORA"
    WHEN DATO FALSE THEN SELECT "NO SE HACE RICA POR QUE NO QUIERE" 
    end case;
end $$

delimiter ;

CALL SOFIA_NO_QUIERE_LEER (TRUE); 

CREATE PROCEDURE SEMAFORO (IN COLOR VARCHAR (5))
BEGIN
-- EJEMPLO SEMAFORO
	CASE color 
    WHEN "ROJO" THEN SELECT "NO PUEDES PASAR";
    WHEN "Ambar" then select "precaucion";
    WHEN "VERDE" THEN SELECT "PUEDES PASAR";
-- EL CASO DE "ELSE" (QUE NO ENTRO EN NINGUN WHEN ANTERIOR NO ES OBLIGATORIO
	ELSE SELECT "COLOR ERRONEO";
	END CASE; 
END $$
    
    DELIMITER ; 
    CALL SEMAFORO ("VERDE");
 