-- actualiza un registro cada dia, a una determinada. Siempre que utilicemos EVENTOS, tenemos que setear la siguiente
-- SIEMPRE QUE UTILICEMOS EVENTOS, TENEMOS QUE SETEAR LA SIGUIENTE

SET GLOBAL EVENT_SCHEDULER = ON; 

DROP SCHEMA IF EXISTS TEST; 
CREATE SCHEMA TEST; 
USE TEST; 

CREATE TABLE GASTOS (
CODIGO INT PRIMARY KEY AUTO_INCREMENT, 
SALDO int
); 

INSERT INTO GASTOS VALUES (DEFAULT, 0);

DROP EVENT IF EXISTS ACTUALIZA_SALDO; 
CREATE EVENT ACTUALIZA_SALDO
ON SCHEDULE EVERY 1 DAY STARTS "2022-09-15 16:40"
DO
	UPDATE GASTOS SET SALDO = 440 WHERE CODIGO = 1;

SELECT * FROM GASTOS; 